### ISSUE TITLE
导表成功后这个报错了，一开始拉代码是好的，导表操作后报错了

### ISSUE THREAD

**Issue by fengyuzheng2020** [TippingGame/F8Framework#12]
Assets/F8Framework/Runtime/Localization/Core/Localization.cs(24,17): error CS0246: The type or namespace name 'LocalizedStrings' could not be found (are you missing a using directive or an assembly reference?)

**Comment by fengyuzheng2020** [comment]
![Snipaste_2024-05-16_21-41-21](https://github.com/TippingGame/F8Framework/assets/63836009/b6cfc5e4-2166-499c-804d-ef6774d9bc22)

**Comment by TippingGame** [comment]
就是没有本地化表，可以手动复制过去再导表一次

**Comment by fengyuzheng2020** [comment]
可以了谢谢
