### ISSUE TITLE
Core\Localization.cs(24,17): error CS0246: The type or namespace name 'LocalizedStrings' could not be found

### ISSUE THREAD

**Issue by uiosun** [TippingGame/F8Framework#2]
`private LocalizedStrings p_LocalizedStrings;`

新更新往里加了什么吗？这个类找不到

**Comment by uiosun** [comment]
能不能打个版本？搞个固定版本只做修复，先用着，后面有需要再升级

**Comment by TippingGame** [comment]
private LocalizedStrings p_LocalizedStrings; 找不到类是因为本地化表格还没创建，已经修改为首次导入包会提示并自动复制表格。
