### ISSUE TITLE
手机多分辨率自适应

### ISSUE THREAD

**Issue by joseph16388** [TippingGame/F8Framework#24]
你好，伟大的工作！请问，可以做个手机多分辨率自适应的Manager模块吗？谢谢！

**Comment by TippingGame** [comment]
多分辨率自适应是指1.适应刘海屏，还是2.横竖屏切换后UI动态适应？3.unity自己带的canvas就可以实现切换分辨率自动适配了

**Comment by joseph16388** [comment]
**我记得我去年用2021版做手机游戏的时候，手动调整的工作量还是有的**

**Comment by TippingGame** [comment]
尝试使用项目中的SafeAreaAdapter.cs
