### ISSUE TITLE
开发工具/截图工具 BUG

### ISSUE THREAD

**Issue by Yogioo** [TippingGame/F8Framework#26]
![image](https://github.com/user-attachments/assets/ccdc7dce-df66-47cd-abcb-eec5ae3a3624)
截图选择目录选择了一个 ScreenShot 文件夹, 实际截图后, 返回的是 项目文件目录下, 我猜测是拼接路径字符串时错误导致的
当前Bug版本 1.0.78

**Comment by TippingGame** [comment]
1.0.83 已修复
