### ISSUE TITLE
在试用ui相关的功能,发现动不动就compiling script,load完过一会又load

### ISSUE THREAD

**Issue by zhimingoh** [TippingGame/F8Framework#4]
就真的很难顶,没动代码
<img width="423" alt="Snipaste_2024-05-05_15-30-00" src="https://github.com/TippingGame/F8Framework/assets/12498344/7657a27e-28f1-4050-9e55-2a40584996c4">

**Comment by zhimingoh** [comment]
这个好像是一直在执行 , 自动获取组件,死循环

**Comment by TippingGame** [comment]
我思考了一下确实不应该自动获取组件，按钮手动触发会直观点

**Comment by zhimingoh** [comment]
这个问题还是很容易造成死循环,一直 load,建议改成手动操作
