### ISSUE TITLE
ToHashSet()和Linq冲突

### ISSUE THREAD

**Issue by zhaige95** [TippingGame/F8Framework#5]
![Snipaste_2024-05-06_00-01-34](https://github.com/TippingGame/F8Framework/assets/41580731/920bd4d9-7ebd-40b7-83b6-cb2207c47402)

以下方法或属性之间的调用具有二义性:“System.Linq.Enumerable.ToHashSet<TSource>(System.Collections.Generic.IEnumerable<TSource>)”和“F8Framework.Core.IEnumerableExts.ToHashSet<T>(System.Collections.Generic.IEnumerable<T>)”[CS0121](https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS0121%29)

**Comment by TippingGame** [comment]
不清楚你的使用方法，这是我的示例，正常调用。
public class MyType
{
    public int Id { get; set; }
    public string Name { get; set; }
}

List<MyType> myEnumerable = new List<MyType>
{
    new MyType { Id = 1, Name = "Item 1" },
    new MyType { Id = 2, Name = "Item 2" },
    new MyType { Id = 3, Name = "Item 3" }
};
// Linq
var myHashSet = System.Linq.Enumerable.ToHashSet(myEnumerable);
// IEnumerableExts
var myHashSet2 = myEnumerable.ToHashSet();

**Comment by zhaige95** [comment]
找到原因了，同时引用了框架和linq导致的，我想知道框架的相关扩展方法是否能覆盖linq的方法，以及框架的扩展实现和linq有什么区别？

**Comment by TippingGame** [comment]
用的还是linq的方法，只不过比linq多了Select参数。如下：
public static HashSet<TKey> ToHashSet<TKey, T>(this IEnumerable<T> @this, Func<T, TKey> keySelector)
{
    return new HashSet<TKey>(@this.Select(keySelector));
}
public static HashSet<TKey> ToHashSet<TKey, T>(this IEnumerable<T> @this, Func<T, TKey> keySelector, IEqualityComparer<TKey> comparer)
{
    return new HashSet<TKey>(@this.Select(keySelector), comparer);
}

**Comment by zhaige95** [comment]
明白了，感谢回复
