### ISSUE TITLE
热更疑问

### ISSUE THREAD

**Issue by WhoWhenLone** [TippingGame/F8Framework#6]
大佬，请问一下
我看热更流程里，对比本地清单里和远端的MD5值，不一样就需要下载，然后所有资源下载完之后，才会更新沙盒里的资源清单
如果下载到一半，退出游戏，再次打开游戏的话，还会从新在下吧，可能是我看漏了哈，倒是没有看到有啥断点续传，缓存啥的的机制。
缓存机制的话，我的想法有两种
1.下载好一个，就在本地清单里写进去，但是感觉IO操作太频繁了
2.构建下载清单时，遍历远端资源清单，本地沙盒或者StreamingAsset下没有的资源，才是需要下载的资源，放到热更下载清单里，进行下载
恳求大佬点播赐教

**Comment by TippingGame** [comment]
感谢提醒，两种方法都挺常用，我后面加上校验资源这一步吧，毕竟校验本地资源稳一点
